export const SIGNUP_BUYER ='SIGNUP_BUYER';
export const SIGNUP_OWNER ='SIGNUP_OWNER';
export const LOGIN_BUYER ='LOGIN_BUYER';
export const LOGIN_OWNER='LOGIN_OWNER';
export const PROFILE_BUYER='PROFILE_BUYER';
export const PROFILE_OWNER='PROFILE_OWNER';
export const BUYER_RESTAURANT_SEARCH='BUYER_RESTAURANT_SEARCH';
export const IMAGE_DOWNLOAD='IMAGE_DOWNLOAD';
export const GET_ITEM='GET_ITEM';
export const GET_SECTION_ITEMS='GET_SECTION_ITEMS';
export const ORDER_ITEM='ORDER_ITEM';
export const GET_ORDERS_NEW='GET_ORDERS_NEW';
export const UPDATE_ORDER='UPDATE_ORDER';
export const GET_ORDERS_OLD='GET_ORDERS_OLD';
export const GET_ALLSECTIONS='GET_ALLSECTIONS';
export const ADD_SECTION='ADD_SECTION';
export const UPDATE_SECTION='UPDATE_SECTION';
export const DELETE_SECTION='DELETE_SECTION';
export const GET_ALLITEMS='GET_ALLITEMS';
export const ADD_ITEM='ADD_ITEM';
export const UPDATE_ITEM='UPDATE_ITEM';
export const DELETE_ITEM='DELETE_ITEM';
export const GET_PROFILE_BUYERDETAILS='GET_PROFILE_BUYERDETAILS';
export const GET_PASTORDERS='GET_PASTORDERS';
export const GET_UPCOMINGORDERS='GET_UPCOMINGORDERS';
export const GET_PROFILE_OWNERDETAILS='GET_PROFILE_OWNERDETAILS';








